name: Auto Push Reasoning Files

on:
  push:
    paths:
      - 'automate_process.py'
      - 'REASONING_LOG.md'
      - 'PATCHLIST.md'
      - 'SUMMARY.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  autopush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install OpenAI SDK
        run: pip install --upgrade openai

      - name: Run automation script
        run: python automate_process.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Auto-commit reasoning files
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "🧠 ULTIMAI reasoning update v1.1"
          file_pattern: 'REASONING_RESULT.md'
