# automate_process.py — ULTIMAI v1.1 (обновлено под OpenAI SDK >=1.0.0)

import openai
import os

# Убедитесь, что у вас установлен openai>=1.0.0
# pip install --upgrade openai

# Получаем API-ключ из переменных окружения или GitHub Secrets
api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    raise ValueError("OPENAI_API_KEY environment variable is required")

# Создаем клиент OpenAI с правильным синтаксисом для SDK >=1.0.0
client = openai.OpenAI(api_key=api_key)

# 📂 Данные для reasoning (примеры)
reasoning_prompt = "Generate a reasoning patch for ULTIMAI memetic loop integrity."

# 🧠 Обновлённый синтаксис для chat/completions с обработкой ошибок
try:
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[
            {"role": "system", "content": "You are a reasoning architect for a self-evolving AI ecosystem."},
            {"role": "user", "content": reasoning_prompt}
        ],
        max_tokens=2000,  # Ограничиваем размер ответа для производительности
        temperature=0.7   # Контролируем креативность
    )
except Exception as e:
    print(f"❌ Ошибка вызова OpenAI API: {e}")
    raise

# 💾 Сохраняем результат с обработкой ошибок
try:
    # Проверяем, что ответ содержит данные
    if not response.choices or not response.choices[0].message.content:
        raise ValueError("API вернул пустой ответ или ответ без содержимого")
    
    output_text = response.choices[0].message.content.strip()
    
    # Дополнительная проверка на пустое содержимое
    if not output_text:
        raise ValueError("API вернул пустое содержимое")
    
    # Безопасная запись файла с обработкой ошибок
    output_file = "REASONING_RESULT.md"
    try:
        with open(output_file, "w", encoding="utf-8", newline='\n') as f:
            f.write("# 🧠 Auto-Generated Reasoning Patch\n\n")
            f.write(f"**Generated at**: {os.environ.get('GITHUB_RUN_ID', 'local')}\n")
            f.write(f"**Model**: gpt-4\n\n")
            f.write("---\n\n")
            f.write(output_text)
            f.write("\n\n---\n")
            f.write("*This content was automatically generated by ULTIMAI reasoning pipeline.*\n")
        
        print(f"✅ {output_file} сгенерирован и готов к коммиту")
        print(f"📊 Размер контента: {len(output_text)} символов")
        
    except IOError as e:
        print(f"❌ Ошибка записи файла {output_file}: {e}")
        raise
        
except Exception as e:
    print(f"❌ Ошибка обработки ответа API: {e}")
    # Создаем файл с информацией об ошибке для отладки
    error_file = "REASONING_ERROR.md"
    try:
        with open(error_file, "w", encoding="utf-8") as f:
            f.write("# ❌ ULTIMAI Reasoning Error\n\n")
            f.write(f"**Error**: {str(e)}\n")
            f.write(f"**Timestamp**: {os.environ.get('GITHUB_RUN_ID', 'local')}\n")
        print(f"📝 Информация об ошибке сохранена в {error_file}")
    except IOError:
        print("❌ Критическая ошибка: не удалось записать файл ошибки")
    raise
