[
build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ultimai"
version = "0.1.0"
description = "ULTIMAI reasoning infrastructure"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["ultimai"]