name: CI

on:
  push:
    branches:
      - main
  pull_request:

# Grant the minimum necessary permissions to run tests, upload artefacts and publish Pages.
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Cancel any in-progress run of this workflow to avoid duplicate builds
    concurrency:
      group: ci
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          # Attempt to install graphviz for pygraphviz if available.  Failures are tolerated.
          sudo apt-get install -y graphviz libgraphviz-dev pkg-config || true

      - name: Install optional Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Install optional dependencies; failure is acceptable in offline environments.
          pip install pygraphviz matplotlib || true

      - name: Run unit tests
        run: |
          # Ensure the package is discoverable via PYTHONPATH.
          export PYTHONPATH="$GITHUB_WORKSPACE/ULTIMAI"
          bash ULTIMAI/scripts/verify_integrity.sh

      - name: Build reasoning graph and report
        run: |
          export PYTHONPATH="$GITHUB_WORKSPACE/ULTIMAI"
          mkdir -p build/graph build/report
          python ULTIMAI/scripts/generate_graph.py --input ULTIMAI/data/seeds.json --output build/graph/graph.json || true
          python ULTIMAI/scripts/dump_report.py --graph build/graph/graph.json --output build/report/report.md
          # Prepare public folder for GitHub Pages
          mkdir -p public/graph public/report
          cp -r build/graph/* public/graph/ || true
          cp -r build/report/* public/report/ || true

      - name: Upload graph artefact
        uses: actions/upload-artifact@v4
        with:
          name: graph
          path: build/graph

      - name: Upload report artefact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: build/report

      - name: Upload Pages artefact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public