name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          # ignore missing imports for packages not present in CI
          flake8 ultimai --count --select=E9,F63,F7,F82 --show-source --statistics || true
      - name: Run self-test example
        run: |
          mkdir -p data
          echo "source_id,source_label,target_id,target_label,relation,source_score,target_score" > data/example.csv
          echo "A,God,B,Logic,influences,0.6,0.7" >> data/example.csv
          echo "B,Logic,C,Absurdity,contradicts,0.7,0.5" >> data/example.csv
          echo "A,God,C,Absurdity,resolves,0.6,0.5" >> data/example.csv
          python cli.py build-graph --input data/example.csv --output data/tmp_graph.json
          python cli.py run-memetic --graph data/tmp_graph.json --iterations 1
          python cli.py run-audit --graph data/tmp_graph.json